language: ruby
notifications:
  email: false
rvm:
- 2.3.1
cache:
- bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
script:
- bundle exec rake spec
- bundle exec rake cucumber
script: bundle exec rake test_with_coveralls
env:
  global:
    secure: BVxcT9o3xy7fur+EkEZ51YvCjWXs8C02l35BKPD/EpHYxqKyY8+3Zb5kLp5QUAyXBibqWNLNdhTcb8miZiQAWXSqjdKnIcnUT8HS/l7f9lwksISoruLAv7UPrisJrYQpOFz9ECIpvRueP8X+O/CVVcw3fHLyNz1oULgUxu5nE1n9L1cTtHRiNLsfO7Xy2pvRMaoAmey/C5iO5tj+gNxnAnSNbr0yt7ke10F9boeeOq5v6a2l9YDCS8HPcqIBYJflU+rPZcy2dAvyyjKpKAR7DKWPB1xvejc8Pz4vzE49fgLYAEscLfhP0co2FYfU4PRfm5v2uTN0+1qdWlSAKZP9CiFClezW/ntVcNryOHdrlGWsu/ifpK6HmcDkQZoS8CK8+RaMuv0tfH7+ydFQzg+4rv6vSVDJiyGOESN0/YqAr5YiEH00SHHVc7ZH2iIeh3Os7YYbFuZJi9J7fujyYZUa+nnC8I4pkjk1JVQiIBq/UVnRWlIWniyorFaeGXi2oV3JgHVon1StkhBF/oqfI103EQ6NVEpyXraLSPvkssyxs/7EAPGNxyFRocOJv246V+AcwYHlQABF3UxPiq4OJJAAkFOQtRONnFdeg3Agfjc1M+6FNsK9auxiJQEQrEqAOA5+Ju6gbmDzc6mapd7rtn2KzrR3YQpqtn0/7lqKVDkbMG4=
